name: PeyajWhitelist
version: 3.0
main: com.peyaj.whitelist.PeyajWhitelist
api-version: 1.21
description: A robust crossplay-compatible whitelist plugin supporting Java and Bedrock Edition players.
softdepend: [Floodgate, LuckPerms, PlaceholderAPI]
commands:
  pwhitelist:
    description: Manage the PeyajWhitelist.
    aliases: [pwl]
    permission: peyajwhitelist.admin
    usage: /pwhitelist <on|off|add|remove|list|reload>
  whitelist:
    description: Manage the PeyajWhitelist (overridden).
    aliases: [wl]
    permission: peyajwhitelist.admin
    usage: /whitelist <on|off|add|remove|list|reload>
